server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:commerce_sample;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    contexts: dev, faker
    change-log: classpath:db/master.xml
    url: jdbc:h2:mem:commerce_sample
