spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./build/h2db/db/ecommerce;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  liquibase:
    contexts: dev, faker
    change-log: classpath:db/master.xml
    url: jdbc:h2:file:./build/h2db/db/ecommerce;DB_CLOSE_DELAY=-1
