server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./build/h2db/db/ecommerce;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false
  liquibase:
    contexts: prod
    change-log: classpath:db/master.xml
    url: jdbc:h2:file:./build/h2db/db/ecommerce;DB_CLOSE_DELAY=-1
